export const USER_ACTION_TYPES = {
    SET_CURRENT_USER: 'USER/SET_CURRENT_USER',
    CHECK_USER_SESSION: 'USER/CHECK_USER_SESSION',
    NO_CURRENT_USER_SESSION: 'USER/NO_CURRENT_USER_SESSION',
    GOOGLE_SIGN_IN_START: 'USER/GOOGLE_SIGN_IN_START', 
    EMAIL_SIGN_IN_START: 'USER/EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'USER/SIGN_IN_SUCCESS',
    SIGN_IN_FAIL: 'USER/SIGN_IN_FAIL'
}

export const USER_INITIAL_STATE = {
    currentUser: null, 
    isLoading: false, 
    error: null,
};