export const CART_ACTION_TYPES = {
    SET_CURRENT_CART_ITEMS: 'CART/SET_CURRENT_CART',
    SET_CURRENT_ISCARTOPEN: 'CART/SET_CURRENT_ISCARTOPEN',
    SUCCESSFUL_PAYMENT_CLEAR_CART: 'CART/SUCCESSFUL_PAYMENT_CLEAR_CART',
};


export const CART_INITIAL_STATE = {
    isCartOpen: false,
    cartItems: [],
};